/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Board: typeof import('./src/components/Board.vue')['default']
    Member: typeof import('./src/components/Member.vue')['default']
    Members: typeof import('./src/components/Members.vue')['default']
    Operation: typeof import('./src/components/Operation.vue')['default']
    PageLoader: typeof import('./src/components/PageLoader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Ship: typeof import('./src/components/Ship.vue')['default']
    Squad: typeof import('./src/components/Squad.vue')['default']
    StandBy: typeof import('./src/components/StandBy.vue')['default']
  }
}
